#AllCops:
#  NewCops: enable

Style/Documentation:
  Enabled: false
Metrics/ClassLength:
  Max: 250
Style/AsciiComments:
  Enabled: false

Lint/DuplicateMethods:
  Exclude:
    - 'instancecounter.rb'

# Сделал это по причине того, что в методах много Puts. Без них я бы везде уместился под требования.
Metrics/MethodLength:
  Max: 15
# Это плохо, но прям совсем критичный метод такой один...
Metrics/AbcSize:
  Max: 50